### ISSUE TITLE
Release 6.0.0?

### ISSUE THREAD

**Issue by cjwatson** [zopefoundation/zope.publisher#57]
I'd like to release 6.0.0, with my changes that switch to `multipart`.  I don't have the relevant PyPI privileges, though.  Are people OK with releasing this, and if so could somebody help out?

**Comment by icemac** [comment]
I am going to add 3.9 support today an then cut a release.

**Comment by icemac** [comment]
See #58 – It has become a bit bigger effort.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.publisher/6.0.0/.
Thank you for holding.

**Comment by cjwatson** [comment]
Thanks for sorting that out!
