### ISSUE TITLE
latest multipart stops parsing after 128 parts

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/zope.publisher#80]
`multipart` commit https://github.com/defnull/multipart/commit/aa9b820e9475763635d2591b94a361f32819640e adds a limit on parsed parts of 128

multipart 1.1.0 definitely has this

That means forms having about 128 widgets (give or take empty-markers and hidden controls) get silently cut at the 128 limit. Good or not submit buttons are usually last so processing does not even get to the button action.

`processInputs` calls `multipart.parse_form_data` with `strict=False` and without `part_limit`.

I might see a reason behind setting a default `part_limit=128` and ignoring parse errors, but not sure whether that's something good or not.

**Comment by defnull** [comment]
A short term solution would be to pass a higher `part_limit` to `parse_form_data()` and maybe re-evaluate the other limits too. In the meantime I'll work on better documentation for those limits, and add a way to receive errors from `parse_form_data()` even in non-strict mode.

**Comment by agroszer** [comment]
We might need to define (or allow app code) to define the limits. We have some highly complex generated z3c.forms which can have loads of widgets.

**Comment by icemac** [comment]
In #82 the default is increased to 1024 parts. As it is done via a global variable it could be patched to even more. (Released in version 7.2.)

So I'd consider this ticket as solved.
